### ISSUE TITLE
Bidirectional Dictionary

### ISSUE THREAD

**Issue by Symbai** [dotnet/corefxlab#2793] opened 2019-12-02 11:42 UTC
I would like to request a new collection type which features fast lookup support in both directions. To make this possible not only the key but also the value has to be unique.

There currently is no collection for this and the workaround of creating two dictionaries but one is reversed increases memory and performance footprints by 2x.

**Comment by gfoidl** [comment] 2019-12-03 11:16
See https://github.com/dotnet/corefxlab/issues/446 and a PR for this at https://github.com/dotnet/corefxlab/pull/2613

**Comment by ahsonkhan** [comment] 2019-12-04 04:46
Closing as duplicate of https://github.com/dotnet/corefxlab/issues/446

**Closed by ahsonkhan** 2019-12-04 04:46 UTC
Labels: area-System.Collections
