### ISSUE TITLE
Span Debugger Viewers Must Work in VS2017

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#1122] opened 2017-01-13 18:28 UTC

**Comment by ahsonkhan** [comment] 2017-04-04 23:28
Is this a duplicate of https://github.com/dotnet/corefx/issues/14376?

**Comment by KrzysztofCwalina** [comment] 2017-11-09 20:04
@ahsonkhan, should this be tracked in corefx now?

**Comment by ahsonkhan** [comment] 2017-11-10 22:03
Yes, the issue in corefx that is already open should be sufficient to track this work.

**Closed by ahsonkhan** 2017-11-10 22:03 UTC
Labels: area-System.Span
