### ISSUE TITLE
Intermittent TestJsonReaderUtf8 failure in CI

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefxlab#2521] opened 2018-10-05 19:10 UTC
Related PR https://github.com/dotnet/corefxlab/pull/2520

```
[xUnit.net 00:00:02.4646706]     System.Text.JsonLab.Tests.JsonReaderTests.TestJsonReaderUtf8(compactData: True, type: ProjectLockJson, jsonString: "{  \"locked\": false,  \"version\": 1,  \"targets\"...) [FAIL]
11:28:28 Skipped  System.Text.JsonLab.Tests.JsonParserTests.ReadJsonSpecialStrings
11:28:28 Failed   System.Text.JsonLab.Tests.JsonReaderTests.TestJsonReaderUtf8(compactData: True, type: ProjectLockJson, jsonString: "{  \"locked\": false,  \"version\": 1,  \"targets\"...)
11:28:28 Error Message:
11:28:28  Assert.Equal() Failure
11:28:28 Expected: 0
11:28:28 Actual:   3376
11:28:28 Stack Trace:
11:28:28    at System.Text.JsonLab.Tests.JsonReaderTests.TestJsonReaderUtf8(Boolean compactData, TestCaseType type, String jsonString) in /mnt/j/workspace/dotnet_corefxlab/master/ubuntu16.04_debug_prtest/tests/System.Text.JsonLab.Tests/JsonReaderTests.cs:line 128
11:28:41 
11:28:41 
Total tests: 255. Passed: 252. Failed: 1. Skipped: 2.
11:28:41 Test Run Failed.
11:28:41 Test execution time: 15.7298 Seconds
11:28:41 Some tests failed in project tests/
```

**Comment by ahsonkhan** [comment] 2018-10-05 20:12
Duplicate of https://github.com/dotnet/corefxlab/issues/2497

**Closed by ahsonkhan** 2018-10-05 20:12 UTC
Labels: area-System.Text.Json, blocking-clean-ci, bug
