### ISSUE TITLE
PollingWatcher tests fail with ObjectDisposedException 

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#2343] opened 2018-06-05 15:43 UTC
Got the following exception when running CI build, yet I did not touch any code in the polling watcher library:

08:40:24 Starting test execution, please wait...
08:40:26 The active test run was aborted. Reason: Unhandled Exception: System.ObjectDisposedException: Cannot access a disposed object.
08:40:26    at System.Threading.TimerQueueTimer.Change(UInt32 dueTime, UInt32 period)
08:40:26    at System.IO.PollingFileSystemWatcher.TimerHandler(Object context) in /mnt/j/workspace/dotnet_corefxlab/master/ubuntu16.04_release_prtest/src/System.IO.FileSystem.Watcher.Polling/System/IO/PollingFileSystemWatcher.cs:line 208
08:40:26    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
08:40:26 --- End of stack trace from previous location where exception was thrown ---
08:40:26    at System.Threading.TimerQueueTimer.CallCallback()
08:40:26    at System.Threading.TimerQueueTimer.Fire()
08:40:26    at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by ahsonkhan** [comment] 2018-06-05 19:23
Duplicate of https://github.com/dotnet/corefxlab/issues/420. Closing.

**Closed by ahsonkhan** 2018-06-05 19:23 UTC
